### ISSUE TITLE
Chat doesn't show incoming messages

### ISSUE THREAD

**Issue by billyjbryant** [kamerat/vs-code-twitch-chat#6] opened 2020-08-07 13:35 UTC
I'm using Twitch Chat 0.0.4 in VS Code-Insiders on Linux. Twitch Chat connects and I can send outbound messages but it doesn't show inbound messages. Not able to find any log files of any value to indicate the error. It also does not seem to support Twitch Emoji. 

### VS Code Build
```
Version: 1.48.0-insider
Commit: 20cba51fb305868238eddc69758d259c29b3230d
Date: 2020-08-07T05:39:52.666Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic snap
```

**Comment by BlitZz96** [comment] 2020-08-07 17:09
Hello, @billyjbryant and thank you for your issue.
I have troubles reproducing your issue. Could you provide me what your twitch chat settings looks like? - without your token that is.

What emojies are you trying to send? Channel spesific/twitch originals/BTTV?

**Comment by kamerat** [comment] 2020-11-14 20:11
I can confirm this is a bug in the twitch-bot package this extention depends on: https://github.com/kritzware/twitch-bot/issues/49

Quick-fix: Change your name in the twitch-chat settings to all lowercase.

**Comment by kamerat** [comment] 2020-11-14 21:30
Fixed in https://github.com/kamerat/vs-code-twitch-chat/commit/5673fcdf6f2fd8e18ceb049cfaae09c2f1df6f61

Will be live in 0.0.5

**Closed by kamerat** 2020-11-14 21:30 UTC
Labels: bug, question
